carpeta_origen: "/Users/cristopherrobledo/Downloads"
carpeta_destino: "/Users/cristopherrobledo/Documents"

filtrado:
  extensiones_agregar: ["png","json", "py"]
  palabras_clave: ["factura", "documento_empresa", "reporte"]

